//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormationOfCriteria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vedomosti
    {
        public string IdVedomosti { get; set; }
        public Nullable<int> IdExam { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<byte> TheNumberOfPointsForTheExam { get; set; }
        public string FinalGrade { get; set; }
        public Nullable<System.DateTime> RecordingDate { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
